### ISSUE TITLE
List of Locations

### ISSUE THREAD

**Issue by Dajanajozanovic** [Dajanajozanovic/capstone-project#1]
## User Story

As a user I want to see all sightseeing Locations.

Description (text, scribble, wireframe, design)
![Unbenannt-2021-06-08-2028](https://user-images.githubusercontent.com/82399097/121439752-d453e280-c986-11eb-8b09-a95d50858fb0.png)
![Unbenannt-2021-06-08-2028-1](https://user-images.githubusercontent.com/82399097/121439760-d74ed300-c986-11eb-99af-ec5f263b3033.png)

## Text:
H1:  App Header for Sightseeing and Restaurants and bars(food&drinks)
H2: Location titles 

## Acceptance Criteria

- [x] Show picture of Locations (always visible)
- [x] Images should have the size: min-width: 320 px, better min.: 600px

## Tasks

- [x]  Future branch
- [x] Create unordered list for Sightseeing page and food&drinks page
- [x] Add 3-5 pictures of Locations in Hamburg with a short "About" text
- [x] Add 3-5 pictures of Restaurants and bars in Hamburg with a short "about" text
- [x] add buttons that links the user to the sightseeing or food and bars page

## Complexity
low

**Comment by badabam** [comment]
You should remove the arrow buttons that expand the card into detail view. They are not part of this story.
