### ISSUE TITLE
Add bookmarks for favorite places 

### ISSUE THREAD

**Issue by Dajanajozanovic** [Dajanajozanovic/capstone-project#10]
As a user
I need to add bookmarks
so that I do not forget about my favorite places in Hamburg.

## Description (Text, Scribble, Wireframe, Design)
![bookmarks-1](https://user-images.githubusercontent.com/82399097/122533997-66608880-d022-11eb-8042-6b6df314cab6.png)

## Acceptance criteria

- [x] When clicking on the bookmark, the icon gets a new color 
- [x] When clicking on the favorite places button, you go to Favorite places side 
- [x] When clicking on the back button, you go back to each side you've been before

## Tasks

- [x]  Create feature branch
- [x] Create active and inactive Bookmark component
- [x] add a Link to favorite page in Navigation
- [x] add back button
- [x] Create Favorite Page
- [x] Write test for favorite Page
