### ISSUE TITLE
Add maritim style

### ISSUE THREAD

**Issue by Dajanajozanovic** [Dajanajozanovic/capstone-project#15]
As a user,
I would love to have an app which shows me the charme of the city I visit. 

##Description (Text, Scribble, Wireframe, Design)
![styling-1](https://user-images.githubusercontent.com/82399097/124391880-fc6b0300-dcf2-11eb-8e9a-48fab73a90e2.png)

## Acceptance

- [x] In the header a gull should have it's place :)
- [x] as bookmarks I need orange anchors 
- [x] the background should have blue colors

## Tasks

- [x] create future branch
- [x]  find icons and add them
- [x] find a color theme that fits (blue, white, orange)
