### ISSUE TITLE
add search bar

### ISSUE THREAD

**Issue by Dajanajozanovic** [Dajanajozanovic/capstone-project#16]
As a user,
I would like to filter restaurant categories (italian, indian food for example)

## Description (Text, Scribble, Wireframe, Design)
![search field](https://user-images.githubusercontent.com/82399097/124392183-89fb2280-dcf4-11eb-9135-ea29a2ff8f7a.png)

## Acceptance

- [x] the search field is positioned in the beginning of the food & drinks site 

## Tasks

- [x]  create future branch
- [x] add a form with an input field to the locations page 
- [x] add a function to map over the api and filter for the reataurant categories
