### ISSUE TITLE
2. Sightseeing detailview

### ISSUE THREAD

**Issue by Dajanajozanovic** [Dajanajozanovic/capstone-project#2]
As a user
I need a detailed view of the sightseeing locations so that I can decide if this location is what I am looking for.

## Description (Text, Scribble, Wireframe, Design)
![Unbenannt-2021-06-01-2212-6](https://user-images.githubusercontent.com/82399097/120721475-32d41900-c4ce-11eb-8560-e9104d9bb084.png)
![Unbenannt-2021-06-01-2212-5](https://user-images.githubusercontent.com/82399097/120721479-349ddc80-c4ce-11eb-8368-88c85b4fbd08.png)

## Acceptance criteria

- [ ] The button hides the details of the locations

## Tasks

- [ ] Add button which hides the details
- [ ] Add basic styling
- [ ] Add buttons under the pictures of the locations to show more details
- [ ] Test on mobile

## Complexity
low
