### ISSUE TITLE
First draft of my home page

### ISSUE THREAD

**Issue by Dajanajozanovic** [Dajanajozanovic/capstone-project#3]
As a user 
I need a home page to select a category that I am interested in. 

## Description (Text, Scribble, Wireframe, Design)
![Unbenannt-2021-06-01-2212-2](https://user-images.githubusercontent.com/82399097/120564626-9d705080-c40b-11eb-9456-268d90040ed3.png)

## Acceptance 

- [x] The navigation buttons are always visible and bring the user to the clicked site
- [x] The app title is position fix
- [x] The two images with text show some details about food&drinks and the sightseeing options in Hamburg

## Tasks

- [x] Add navigation with function 
- [x] Add styling
- [x] Write test on mobile

## Complexity
low
