### ISSUE TITLE
Fetch of an API or download a data.json

### ISSUE THREAD

**Issue by Dajanajozanovic** [Dajanajozanovic/capstone-project#6]
As a user,
I need a list of locations so that I can get a better overview of the possibilities for undertaking.

## Description (Text, Scribble, Wireframe, Design)
![fetch locations](https://user-images.githubusercontent.com/82399097/121869648-8f230e00-cd02-11eb-9b36-3e59ce107da1.png)

## Acceptance

- [x] the App title should be in a fix position
- [x] the title and should be visible
- [x] the button shows on click more details about each location

## Tasks

- [x] fetch the FSQ API and filter for locations in Hamburg
- [x] add basic style
