### ISSUE TITLE
Add 'parks' side with map

### ISSUE THREAD

**Issue by Dajanajozanovic** [Dajanajozanovic/capstone-project#8]
As a user,
I need a map of parks so that I can get a better overview of the parks in Hamburg and also the ones which are close to my location.

## Description (Text, Scribble, Wireframe, Design)
![parks-1](https://user-images.githubusercontent.com/82399097/122460233-2b267100-cfb2-11eb-9f2b-b1774eec5e1c.png)

## Acceptance

- [ ] the map shows the parks and the parks are highlighted with a tree icon
- [ ] when the user hovers over a tree icon it shows the exact address of the location

## Tasks

- [ ] create future branch 
- [ ] find icons and add them 
- [ ] use hooks?
